### ISSUE TITLE
Feature request:  Push to MQTT instead of InfluxDB

### ISSUE THREAD

**Issue by whiteduck22** [eargollo/smartthings-influx#25]
Hi there,

Since Groovy was discontinued for me last week I lost my sensor data that I used to pass to MQTT (and then into Home Assistant) and the alternative options seem tricky and rely on custom webhooks to workaround this.

Would your code be able to push the payload to an MQTT bus instead of the InfluxDB?  I am not a proficient coder to figure this out so my apologies!

Thanks a lot
Ian

**Comment by whiteduck22** [comment]
Actually I think that could be really useful to many people who just want sensor / state information to flow into another HA solution but don't want to fully integrate it...

**Comment by eargollo** [comment]
I haven't read much about MQTT but I suppose it should be feasible to push events from the current code. 

The only potential issue I see is that it would not be true event based since this codebase does periodic pooling in SmartThings. If we pool every 5 minutes, you would only know the state at 5 minutes interval. Also, for sensors (motion for example), you would not receive events when it detects something or when it gets cleared. Only the existing state at the moment we pull data from SmartThings.

I have been giving some thought about the code becoming real event driven but I haven't found webhooks at the SmartThings API.

Would "periodic events"  do the trick for your usecase?

**Comment by whiteduck22** [comment]
Yes for my use case periodic update would be OK - I was thinking for things like temperature but I know it's not ideal.  Not sure of the API throttling i.e. do Samsung allow us to call the APIs once every 60 seconds or could we filter it down to a few devices and 'watch' them on a more frequent interval.  I know @TAustin has built an Edge gateway with a webhook using ngrok.  I guess IFTTT could be explored also to do the event based stuff?   Thanks again and appreciate what you have done so far!

**Comment by whiteduck22** [comment]
Hi there - I have decided to go down the official Home Assistant to SmartThings integration using Nabu Casa...  I know this is not as fool proof as a local connection as it relies on Cloud connectivity but so far so good.  Thank you for your support!

**Comment by eargollo** [comment]
Thanks for letting me know. Sounds like a promising path.
