### ISSUE TITLE
Case in valuemap

### ISSUE THREAD

**Issue by martyweb** [eargollo/smartthings-influx#32]
I have a key that has uppercase letters that do not match how they are stored in the map.

Key: thermostatFanMode
Map: map[switch:map[off:0 on:1] thermostatfanmode:map[auto:0] thermostatmode:map[auto:3 cool:1 heat:2 off:0]]

I debugged this a little and by passing in a lowercase key it seemed to resolve the problem.

File: monitor.go
Method: Run()
convValue, err := val.FloatValue(strings.ToLower(key))

Should the map be storing the proper case for the key?

**Comment by eargollo** [comment]
The idea was to avoid confusion while writing but I should have either checked both ends at lowercase, or made it the way it is set in SmartThings.

Thanks for bringing that up. I am leaning towards making both lowercase to avoid breaking others.

**Comment by martyweb** [comment]
I'm guessing lower casing everything would be perfectly fine.

I have never seen a situation like this but should you leave the case in there? For example, will it need to account for a "switch" and also a "Switch" type?

**Comment by eargollo** [comment]
I did dig into the problem. The problem is that the library I use to read configuration converts all the keys to lowercase (https://github.com/spf13/viper/issues/371). I haven't taken the approach mentioned in the link and now I get lowercase keys.

In order to solve it, I would need to change the configuration settings, potentially breaking backward compatibility for everyone using the current format. I will think about that moving forward.

**Comment by martyweb** [comment]
Maybe add a config param that can turn case sensitivity off/on?

**Comment by eargollo** [comment]
Bug is solved on v0.3.1.

I will need to work on the long term solution based on fixed tags.
